FROM gcr.io/distroless/base-debian10

ARG EXECUTABLE_NAME
ARG MONGODB_USER
ARG MONGODB_PASSWORD

COPY ${EXECUTABLE_NAME} .

EXPOSE 6464

USER nonroot:nonroot

ENV MONGODB_USER=$MONGODB_USER
ENV MONGODB_PASSWORD=$MONGODB_PASSWORD

ENTRYPOINT ["/${EXECUTABLE_NAME}"]
